[package]
name = "wg-toolkit-cli"
version = "0.4.1"
authors = ["Théo Rozier <contact@theorozier.fr>"]
edition = "2021"
license = "MIT"
description = "Command line utility for interacting with codecs distributed by Wargaming.net"
categories = ["games", "parsing", "data-structures", "command-line-utilities"]
homepage = "https://github.com/mindstorm38/wg-toolkit-rs"
repository = "https://github.com/mindstorm38/wg-toolkit-rs"
readme = "../README.md"

[dependencies]
wg-toolkit = { path = "../wg-toolkit", version = "0.4.0" }
clap = { version = "4.5", features = ["derive", "wrap_help"] }

thiserror = "1.0"

crossbeam-channel = "0.5"

blowfish = "0.9"
rsa = "0.8"

[[bin]]
name = "wgtk"
path = "src/main.rs"
